#!name=Chipper 辅助
#!desc=1.跳过人脸认证 2.显示入金界面


[MITM]
hostname = %APPEND% auth.chippercash.com, api.chippercash.com

[Script]
# 跳过人脸认证
http-response ^https:\/\/auth\.chippercash\.com\/session\/status(?:\?.*)?$ script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/Surge/ChipperCash/js/skipFrozen.js,requires-body=1

# 展示入金界面
http-response ^https:\/\/api\.chippercash\.com\/v1\/users\/accounts\/configuration(?:\?.*)?$ script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/Surge/ChipperCash/js/showUSDXDeposits.js,requires-body=1