#!name=Chipper 辅助
#!desc=1.显示入金界面 2.获取Data


[MITM]
hostname = %APPEND% api.chippercash.com

[Script]
# 获取Data
http-request ^https:\/\/api\.chippercash\.com\/v1\/assets\/historical-prices script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Shadowrocket/js/skipFrozen.js, requires-body=1

# 展示入金界面
http-response ^https:\/\/api\.chippercash\.com\/v1\/users\/accounts\/configuration(?:\?.*)?$ script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Shadowrocket/js/showUSDXDeposits.js, requires-body=1

