#!name=Chipper 辅助
#!desc=1.跳过人脸认证 2.显示入金界面


[MITM]
hostname = %APPEND% auth.chippercash.com, api.chippercash.com

[Script]
# 跳过人脸认证
http-response ^https:\/\/api\.chippercash\.com\/v1\/referrals\/code(?:\?.*)?$ script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Shadowrocket/js/skipFrozen.js,requires-body=1

# 展示入金界面
http-response ^https:\/\/api\.chippercash\.com\/v1\/users\/accounts\/configuration(?:\?.*)?$ script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Shadowrocket/js/showUSDXDeposits.js,requires-body=1