#!name=Chipper 辅助
#!desc=1.跳过人脸认证 2.显示入金界面


[MITM]
hostname = %APPEND% auth.chippercash.com, api.chippercash.com

[Script]
# 展示入金界面
usdt=type=http-response,pattern=^https:\/\/api\.chippercash\.com\/v1\/users\/accounts\/configuration, script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Surge/js/showUSDXDeposits.js, requires-body=1

# 邮箱验证人脸
frozen=type=http-response,pattern=https://compliance.chippercash.com/account/configuration, script-path=https://raw.githubusercontent.com/Argun-Team/Script/main/ChipperCash/Surge/js/skipFrozen.js, requires-body=1
